.TH MYSTRCAT 3 "September 2025" "libmyutils" "Library Functions Manual"
.SH NAME
mystrcat \- concatenate two strings
.SH SYNOPSIS
.B #include <mystrfunctions.h>
.PP
.BI "int mystrcat(char *" dest ", const char *" src );
.SH DESCRIPTION
The
.B mystrcat
function appends the string pointed to by
.I src
to the end of the string pointed to by
.I dest.
The destination buffer must have enough space for the combined string.
.SH RETURN VALUE
Returns 0 on success, or \-1 on error.
.SH AUTHOR
Rayyan Jafar mrayyanjafar11@gmail.com
